name = "first-place-site"
main = "src/index.js"
compatibility_date = "2026-09-07"
workers_dev = true

[[routes]]
pattern = "watchfirstplace.com"
custom_domain = true

[assets]
directory = "./public/"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "GAME_CONTACTS"
id = "e027d550dd1c4bbca2c725315a307526"
